apiVersion: v1
data:
  billing-password: {{ blue_vault.billing.billing_password | string | b64encode  }}
  billing-user: {{ blue_vault.billing.billing_user | string | b64encode  }}
kind: Secret
metadata:
  name: billing
  namespace: blue-prd
type: Opaque
